# Generated by Django 5.2 on 2025-04-13 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandsite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concert',
            name='details',
        ),
        migrations.RemoveField(
            model_name='concert',
            name='title',
        ),
        migrations.RemoveField(
            model_name='member',
            name='image',
        ),
        migrations.AddField(
            model_name='concert',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='member',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='members_photos/'),
        ),
        migrations.AlterField(
            model_name='album',
            name='cover',
            field=models.ImageField(upload_to='album_covers/'),
        ),
        migrations.AlterField(
            model_name='album',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='album',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='concert',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='concert',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='bio',
            field=models.TextField(default=''),
        ),
    ]
